Less subshells (#28)
* only detect package manager once

* get_default_value(): avoid unneeded subshell

* status_service(): improve config values extraction

* create_hotplug_script(): avoid subshell

* status_service(): correctly set gameqdisc default value

* status_service(): make variables local

* start_service(): avoid unnecessary pipe

* stop_service(): avoid unnecessary pipe

* status_service(): don't source functions.sh (sourced by rc.common)

* start_service(): remove extra whitespaces

* stop_service(): remove extra whitespace

* status_service(): make var local

* check for valid package manager before attempting to use it

diff --git a/etc/init.d/qosmate b/etc/init.d/qosmate
--- a/etc/init.d/qosmate
+++ b/etc/init.d/qosmate
@@ -57,10 +57,22 @@ detect_package_manager() {
     fi
 }
 
+# Check for valid package manager
+check_pkg_manager() {
+    case "$1" in
+        apk|opkg)
+            ;;
+        *)
+            logger -s -t qosmate -p user.err "Error: Unexpected package manager '$1'."
+            return 1
+            ;;
+    esac
+    :
+}
+
 # Check if a package is installed
 check_package() {
     local pkg="$1"
-    local pkg_manager=$(detect_package_manager)
     
     case "$pkg_manager" in
         "apk")
@@ -78,10 +90,11 @@ check_package() {
 }
 
 install_packages() {
-    local pkg_manager=$(detect_package_manager)
     # Flag to indicate if opkg update is needed    
     local need_update=0
-    
+
+    check_pkg_manager "$pkg_manager" || return 1
+
     # Check if any packages are missing
     for pkg in $REQUIRED_PACKAGES; do
         if ! check_package "$pkg"; then
@@ -130,7 +143,6 @@ install_packages() {
 }
 
 check_package_status() {
-    local pkg_manager=$(detect_package_manager)
     local missing_packages=""
     
     for pkg in $REQUIRED_PACKAGES; do
@@ -173,16 +185,21 @@ create_hotplug_script() {
 #!/bin/sh
 
 [ -n "$DEVICE" ] || exit 0
-[ "$ACTION" = ifup ] && {
-    enabled=$(uci get qosmate.global.enabled 2>/dev/null)
-    if [ "$enabled" = "1" ]; then
+if [ "$ACTION" = ifup ]; then
+    . /lib/functions.sh
+    config_load qosmate || {
+        logger -t qosmate -p user.err "Failed to load config."
+        exit 1
+    }
+    config_get qosmate_enabled global enabled
+    if [ "$qosmate_enabled" = "1" ]; then
+        logger -t qosmate "Reloading qosmate.sh due to $ACTION of $INTERFACE ($DEVICE)"
         /etc/init.d/qosmate enable
         /etc/init.d/qosmate restart
-        logger -t qosmate "Reloading qosmate.sh due to $ACTION of $INTERFACE ($DEVICE)"
     else
         logger -t qosmate "qosmate is disabled in the configuration. Not executing the script."
     fi
-}
+fi
 EOF
 }
 
@@ -261,13 +278,13 @@ manage_custom_rules_file() {
 start_service() {
     install_packages
     download_scripts
-    create_hotplug_script  # Create the hotplug script instead of downloading it    
-    check_and_download_config || return 1    
-    migrate_config 
+    create_hotplug_script  # Create the hotplug script instead of downloading it
+    check_and_download_config || return 1
+    migrate_config
 
     # Enable the global option
     uci set qosmate.global.enabled='1'
-    uci commit qosmate    
+    uci commit qosmate
 
     # Save the current WAN interface to a temporary file
     load_config
@@ -275,12 +292,12 @@ start_service() {
 
     # Create custom rules file if it doesn't exist
     manage_custom_rules_file create
-    nft -f /etc/qosmate.d/custom_rules.nft    
+    nft -f /etc/qosmate.d/custom_rules.nft
 
-    /etc/qosmate.sh    
+    /etc/qosmate.sh
     /etc/init.d/firewall reload
-    echo "Service started" | logger -t qosmate    
-    /etc/init.d/qosmate enable     
+    logger -t qosmate "Service started"
+    /etc/init.d/qosmate enable
 }
 
 stop_service() {
@@ -311,7 +328,7 @@ stop_service() {
     ## Delete the old qdiscs and IFB associated with the old WAN interface
     tc qdisc del dev "$OLD_WAN" root > /dev/null 2>&1
     tc qdisc del dev ifb-"$OLD_WAN" root > /dev/null 2>&1
-    tc qdisc del dev "$OLD_WAN" ingress > /dev/null 2>&1 
+    tc qdisc del dev "$OLD_WAN" ingress > /dev/null 2>&1
 
     # Remove IFB interface
     ip link del ifb-"$OLD_WAN" 2>/dev/null
@@ -324,39 +341,38 @@ stop_service() {
     echo "Reloading network service..."
     /etc/init.d/network reload
     /etc/init.d/firewall reload
-    echo "Service stopped" | logger -t qosmate     
+    logger -t qosmate "Service stopped"
     exit 0
 }
 
 status_service() {
     # Load configuration
-    . /lib/functions.sh
     config_load 'qosmate'
 
     # Function to extract default values from the main script
     get_default_value() {
         local var_name="$1"
-        local default_value="$(grep "^$var_name=" /etc/qosmate.sh | cut -d'=' -f2- | tr -d '"')"
-        echo "$default_value"
+        grep "^$var_name=" /etc/qosmate.sh | cut -d'=' -f2- | tr -d '"'
     }
 
-    # Function to get current value or default
-    get_current_or_default() {
-        local uci_path="$1"
-        local default_value="$2"
-        local value="$(uci -q get "$uci_path")"
-        if [ -z "$value" ]; then
-            echo "$default_value (Default value)"
-        else
-            echo "$value"
-        fi
-    }
+    # Get current values, replace with defaults if not set
+    local WAN UPRATE DOWNRATE GAMEUP GAMEDOWN gameqdisc
+    config_get WAN settings WAN
+    : "${WAN:="$(get_default_value DEFAULT_WAN)"}"
+    config_get UPRATE settings UPRATE
+    : "${UPRATE:="$(get_default_value DEFAULT_UPRATE)"}"
+    config_get DOWNRATE settings DOWNRATE
+    : "${DOWNRATE:="$(get_default_value DEFAULT_DOWNRATE)"}"
 
-    # Extract default values
-    DEFAULT_WAN=$(get_default_value "DEFAULT_WAN")
-    DEFAULT_DOWNRATE=$(get_default_value "DEFAULT_DOWNRATE")
-    DEFAULT_UPRATE=$(get_default_value "DEFAULT_UPRATE")
-    DEFAULT_GAMEQDISC=$(get_default_value "gameqdisc")
+    config_get ROOT_QDISC settings ROOT_QDISC "hfsc"
+    config_get gameqdisc hfsc gameqdisc
+    : "${gameqdisc:="$(get_default_value DEFAULT_GAMEQDISC)"}"
+
+    # For default GAMEUP and GAMEDOWN, we need to evaluate the expressions
+    config_get GAMEUP hfsc GAMEUP
+    : "${GAMEUP:=$((UPRATE*15/100+400))}"
+    config_get GAMEDOWN hfsc GAMEDOWN
+    : "${GAMEDOWN:=$((DOWNRATE*15/100+400))}"
 
     echo "==== qosmate Status ===="
     
@@ -368,8 +384,7 @@ status_service() {
     fi
 
     # Check if traffic shaping is active
-    WAN=$(uci -q get qosmate.settings.WAN || echo "$DEFAULT_WAN")
-    IFB="ifb-$WAN"
+    local IFB="ifb-$WAN"
     
     if tc qdisc show dev "$WAN" 2>/dev/null | grep -q "qdisc cake"; then
         if /etc/init.d/qosmate enabled; then
@@ -400,25 +415,20 @@ status_service() {
 
     echo "==== Current Settings ===="
     # Show summary of current settings
-    echo "Upload rate: $(get_current_or_default qosmate.settings.UPRATE "$DEFAULT_UPRATE") kbps"
-    echo "Download rate: $(get_current_or_default qosmate.settings.DOWNRATE "$DEFAULT_DOWNRATE") kbps"
+    echo "Upload rate: $UPRATE kbps"
+    echo "Download rate: $DOWNRATE kbps"
     
-    # For GAMEUP and GAMEDOWN, we need to evaluate the expressions
-    UPRATE=$(uci -q get qosmate.settings.UPRATE || echo "$DEFAULT_UPRATE")
-    DOWNRATE=$(uci -q get qosmate.settings.DOWNRATE || echo "$DEFAULT_DOWNRATE")
-    DEFAULT_GAMEUP=$((UPRATE*15/100+400))
-    DEFAULT_GAMEDOWN=$((DOWNRATE*15/100+400))
-    
-    echo "Game traffic upload: $(get_current_or_default qosmate.hfsc.GAMEUP "$DEFAULT_GAMEUP") kbps"
-    echo "Game traffic download: $(get_current_or_default qosmate.hfsc.GAMEDOWN "$DEFAULT_GAMEDOWN") kbps"
-    if [ "$(get_current_or_default qosmate.settings.ROOT_QDISC "hfsc")" = "cake" ]; then
+    echo "Game traffic upload: $GAMEUP kbps"
+    echo "Game traffic download: $GAMEDOWN kbps"
+    if [ "$ROOT_QDISC" = "cake" ]; then
         echo "Queue discipline: CAKE (Root qdisc)"
     else
-        echo "Queue discipline: $(get_current_or_default qosmate.hfsc.gameqdisc "$DEFAULT_GAMEQDISC") (for game traffic in HFSC)"
+        echo "Queue discipline: $gameqdisc (for game traffic in HFSC)"
     fi
 
     echo "==== Package Status ===="
-    if check_package_status; then
+
+    if check_pkg_manager "$pkg_manager" && check_package_status; then
         echo "All required packages are installed."
     else
         echo "Some required packages are missing. QoSmate may not function correctly."
@@ -625,13 +635,14 @@ auto_setup() {
                 SPEEDTEST_CMD="speedtest --simple"
             else
                 echo "Neither speedtest-go nor python3-speedtest-cli is installed. Attempting to install speedtest-go..."
+                check_pkg_manager "$pkg_manager" || return 1
                 
                 # Check for sufficient space (adjust the required space as needed)
                 FREE_SPACE=$(df /overlay | awk 'NR==2 {print $4}')
                 if [ "$FREE_SPACE" -lt 15360 ]; then  # Assuming 15MB for speedtest-go
                     echo "Not enough space for speedtest-go. Attempting to install python3-speedtest-cli instead..."
                 else
-                    case "$(detect_package_manager)" in
+                    case "$pkg_manager" in
                         "apk")
                             apk update && apk add speedtest-go
                             ;;
@@ -653,7 +664,7 @@ auto_setup() {
                         echo "Auto-setup cannot continue. Please free up some space and try again."
                         return 1
                     fi
-                    case "$(detect_package_manager)" in
+                    case "$pkg_manager" in
                         "apk")
                             apk update && apk add python3-speedtest-cli
                             ;;
@@ -792,13 +803,14 @@ auto_setup_noninteractive() {
             SPEEDTEST_CMD="speedtest --simple"
         else
             echo "Neither speedtest-go nor python3-speedtest-cli is installed. Attempting to install speedtest-go..."
-            
+            check_pkg_manager "$pkg_manager" || return 1
+
             # Check for sufficient space (adjust the required space as needed)
             FREE_SPACE=$(df /overlay | awk 'NR==2 {print $4}')
             if [ "$FREE_SPACE" -lt 15360 ]; then  # Assuming 15MB for speedtest-go
                 echo "Not enough space for speedtest-go. Attempting to install python3-speedtest-cli instead..."
             else
-                case "$(detect_package_manager)" in
+                case "$pkg_manager" in
                     "apk")
                         apk update && apk add speedtest-go
                         ;;
@@ -820,7 +832,7 @@ auto_setup_noninteractive() {
                     echo "Auto-setup cannot continue. Please free up some space and try again."
                     return 1
                 fi
-                case "$(detect_package_manager)" in
+                case "$pkg_manager" in
                     "apk")
                         apk update && apk add python3-speedtest-cli
                         ;;
@@ -977,3 +989,5 @@ expand_config() {
 
     echo "Configuration expanded successfully. You can now edit all available options in $config_file"
 }
+
+pkg_manager="$(detect_package_manager)" # global variable
