Add custom_rules functions

diff --git a/etc/init.d/qosmate b/etc/init.d/qosmate
--- a/etc/init.d/qosmate
+++ b/etc/init.d/qosmate
@@ -5,12 +5,13 @@ STOP=99
 
 USE_PROCD=1
 
-EXTRA_COMMANDS="check_version update auto_setup expand_config auto_setup_noninteractive"
+EXTRA_COMMANDS="check_version update auto_setup expand_config auto_setup_noninteractive validate_custom_rules"
 EXTRA_HELP="        check_version   Check for updates
         update          Update qosmate
         auto_setup      Automatically configure qosmate
         expand_config   Expand the configuration with all possible options
-        auto_setup_noninteractive   Automatically configure qosmate with no interaction"        
+        auto_setup_noninteractive   Automatically configure qosmate with no interaction
+        validate_custom_rules    Validate custom rules"
 
 REQUIRED_PACKAGES="kmod-sched ip-full kmod-veth tc-full kmod-netem kmod-sched-ctinfo kmod-ifb kmod-sched-cake"
 SCRIPT_URL="https://raw.githubusercontent.com/hudra0/qosmate/main/etc/qosmate.sh"
@@ -24,6 +25,29 @@ service_triggers() {
 load_config() {
     config_load 'qosmate'
     config_get WAN settings 'WAN' 'eth1'
+}
+
+validate_custom_rules() {
+    local tmp_file="/tmp/qosmate_custom_rules_validation.txt"
+    local rules_file="/etc/qosmate.d/custom_rules.nft"
+
+    if [ ! -f "$rules_file" ]; then
+        echo "Custom rules file not found." | tee "$tmp_file"
+        return 1
+    fi
+
+    nft_output=$(nft --check --file "$rules_file" 2>&1)
+    nft_exit_code=$?
+
+    echo "$nft_output" | tee "$tmp_file"
+
+    if [ $nft_exit_code -eq 0 ]; then
+        echo "Custom rules validation successful." | tee -a "$tmp_file"
+        return 0
+    else
+        echo "Custom rules validation failed." | tee -a "$tmp_file"
+        return 1
+    fi
 }
 
 install_packages() {
@@ -153,6 +177,25 @@ config global '\''global'\''\n    option enabled '\''1'\''\n' $CONFIG_FILE
     fi
 }
 
+manage_custom_rules_file() {
+    local action="$1"
+    
+    case "$action" in
+        create)
+            # Ensure the directory exists
+            [ ! -d "/etc/qosmate.d" ] && mkdir -p "/etc/qosmate.d"
+            
+            # Create the file if it doesn't exist
+            [ ! -f "/etc/qosmate.d/custom_rules.nft" ] && touch "/etc/qosmate.d/custom_rules.nft"
+
+            ;;
+        delete)
+            # Not used at the moment...
+            rm -f "/etc/qosmate.d/custom_rules.nft"
+            ;;
+    esac
+}
+
 start_service() {
     install_packages
     download_scripts
@@ -163,6 +206,10 @@ start_service() {
     # Enable the global option
     uci set qosmate.global.enabled='1'
     uci commit qosmate    
+
+    # Create custom rules file if it doesn't exist
+    manage_custom_rules_file create
+    nft -f /etc/qosmate.d/custom_rules.nft    
 
     /etc/qosmate.sh    
     /etc/init.d/firewall reload
@@ -178,6 +225,9 @@ stop_service() {
     # Disable the global option
     uci set qosmate.global.enabled='0'
     uci commit qosmate
+
+    # Remove custom rules table
+    nft delete table inet qosmate_custom 2>/dev/null
 
     ## Delete files
     rm -f /etc/hotplug.d/iface/13-qosmateHotplug
