qosmate init: improve handling of missing files - Do not fail on reg files missing - Report all missing files for given component before failing - Print advisory message when automatic installation repair fails

diff --git a/etc/init.d/qosmate b/etc/init.d/qosmate
--- a/etc/init.d/qosmate
+++ b/etc/init.d/qosmate
@@ -223,25 +223,31 @@ are_var_names_safe() {
 # 0 - OK
 # 1 - general error
 # 2 - missing files
-# 3 - non-matching md5sums
+# 3 - missing reg file
+# 4 - non-matching md5sums
 check_files_integrity() {
-    local reg_file file files file_types component="$1"
+    local files_missing='' reg_missing='' reg_file file files file_types component="$1"
 
-    files=
     eval "file_types=\"\${QOSMATE_FILE_TYPES_${component}}\"
         reg_file=\"\${QOSMATE_FILES_REG_PATH_${component}}\""
+
+    [ -f "$reg_file" ] || reg_missing=1
 
     files="$(print_file_list "$component" ALL)" && [ -n "$files" ] ||
         { error_out "Failed to get file list for component '$component'."; return 1; }
     
     local IFS="$_NL_"
-    for file in ${reg_file}${_NL_}${files}; do
-        [ -n "$file" ] || continue
-        [ -f "$file" ] || { error_out "Missing file: '$file'."; return 2; }
+    for file in $files; do
+        [ -z "$file" ] || [ -f "$file" ] && continue
+        error_out "Missing file: '$file'."
+        files_missing=1
     done
 
     IFS="$DEFAULT_IFS"
-    md5sum -c "$reg_file" &>/dev/null || return 3
+    [ -z "$files_missing" ] || return 2
+    [ -z "$reg_missing" ] || { error_out "$reg_file is not found. Can not check files integrity."; return 3; }
+
+    md5sum -c "$reg_file" &>/dev/null || return 4
     :
 }
 
@@ -1181,7 +1187,10 @@ load_config() {
 validate_config() {
     local file miss_sec_f="/tmp/qosmate-missing-sections" miss_opt_f="/tmp/qosmate-missing-options"
     for file in "$QOSMATE_CFG_FILE" "$QOSMATE_DEFAULTS_FILE"; do
-        [ -f "$file" ] || { error_out "$file not found."; return 1; }
+        [ -f "$file" ] || {
+            error_out "$file not found."
+            return 1
+        }
     done
 
     awk -v miss_sec_f="$miss_sec_f" -v miss_opt_f="$miss_opt_f" \
@@ -1754,10 +1763,11 @@ start_service() {
     # Check files and re-fetch them if any are missing
     for component in $QOSMATE_COMPONENTS; do
         check_files_integrity "$component"
-        case $? in
+        rv=$?
+        case $rv in
             0) ;; # integrity OK
             1) return 1 ;;
-            2) # missing files
+            2|3) # missing files
                 local fix_upd_channel='' fix_version='' force_version=''
                 case "$component" in
                     BACKEND) fix_version="$VERSION" fix_upd_channel="$UPD_CHANNEL" ;;
@@ -1768,8 +1778,16 @@ start_service() {
                     *) force_version="-W $fix_version"
                 esac
                 : "${fix_upd_channel:=release}"
-                update -U "$fix_upd_channel" $force_version -c "$component" || return 1 ;;
-            3) ;; # non-matching md5sums
+                if ! update -U "$fix_upd_channel" $force_version -c "$component"; then
+                    log_msg -warn "Failed to fix qosmate installation automatically."
+                    [ $rv = 2 ] && {
+                        log_msg "Either connect to the Internet and run '/etc/init.d/qosmate start' to have missing files automatically fetched," \
+                        "or manually download and save them in designated paths."
+                        return 1
+                    }
+                    # Do not fail on missing reg files
+                fi ;;
+            4) ;; # non-matching md5sums
         esac
     done
 
