update(): generalize components update

diff --git a/etc/init.d/qosmate b/etc/init.d/qosmate
--- a/etc/init.d/qosmate
+++ b/etc/init.d/qosmate
@@ -533,7 +533,7 @@ update() {
     }
 
     local force_update=0
-    local file_path origin notify_origin fetch_cmd backend_path_prefix frontend_path_prefix version ver_fs component
+    local origin notify_origin fetch_cmd backend_path_prefix frontend_path_prefix version ver_fs component
     local local_backend_version local_frontend_version remote_backend_version remote_frontend_version
 
     if [ "$QOSMATE_FORCE" = "1" ]; then
@@ -571,7 +571,7 @@ update() {
             version="$(eval "$fetch_cmd" "$fetch_path" | awk_get_version "$ver_pattern" "$ver_fs")" &&
             validate_version "$version" ||
             {
-                echo "Failed to get $origin version for $component file at path '$fetch_path'."
+                echo "Failed to get $origin version for $component file at path '$fetch_path'." >&2
                 return 1
             }
 
@@ -600,67 +600,72 @@ update() {
 
     echo "Updating QoSmate..."
 
-    # Update backend
-    if [ "$force_update" -eq 1 ] || [ "$local_backend_version" != "$remote_backend_version" ]; then
-        echo "Updating backend..."
+    for component in backend frontend; do
+        local local_version remote_version js_file js_files gen_file gen_files exec_files exec_file fetch_base_url notify_component
 
-        # !! This relies on remote file path suffix matching local file path
-        for file_path in \
-            "/etc/qosmate.sh" \
-            "/etc/init.d/qosmate" \
-            "/etc/hotplug.d/iface/13-qosmateHotplug"; \
-        do
-            wget -O "$file_path" "${QOSMATE_BASE_URL}${file_path}" || {
-                echo "Command 'wget -O \"$file_path\" \"${QOSMATE_BASE_URL}${file_path}\"' exited with code $?."
-                echo "Backend update failed."
-                return 1
-            }
-        done
+        eval "local_version=\"\${local_${component}_version}\""
+        eval "remote_version=\"\${remote_${component}_version}\""
 
-        chmod +x /etc/qosmate.sh /etc/init.d/qosmate || {
-            echo "Failed to make files '/etc/qosmate.sh', '/etc/init.d/qosmate' executable."
-            return 1
-        }
+        case "$component" in
+            backend)
+                notify_component=Backend
+                fetch_base_url="${QOSMATE_BASE_URL}"
+                js_files=
+                gen_files=" \
+                    /etc/qosmate.sh \
+                    /etc/init.d/qosmate \
+                    /etc/hotplug.d/iface/13-qosmateHotplug"
+                exec_files=" \
+                    /etc/qosmate.sh \
+                    /etc/init.d/qosmate"
+                ;;
+            frontend)
+                notify_component=Frontend
+                fetch_base_url="${QOSMATE_FRONTEND_BASE_URL}/root"
+                js_files="settings hfsc cake advanced rules connections custom_rules"
+                gen_files=" \
+                    /usr/share/luci/menu.d/luci-app-qosmate.json \
+                    /usr/share/rpcd/acl.d/luci-app-qosmate.json \
+                    /usr/libexec/rpcd/luci.qosmate"
+                exec_files="/usr/libexec/rpcd/luci.qosmate"
+        esac
 
-        echo "Backend update complete."
-    fi
+        if [ "$force_update" -eq 1 ] || [ "$local_version" != "$remote_version" ]; then
+            printf '\n%s\n' "Updating $component..."
 
-    # Update frontend
-    if [ "$force_update" -eq 1 ] || [ "$local_frontend_version" != "$remote_frontend_version" ]; then
-        echo "Updating frontend..."
+            # !! This relies on remote file path suffix matching local file path
+            for gen_file in $gen_files; do
+                wget -O "$gen_file" "${fetch_base_url}${gen_file}" || {
+                    echo "Command 'wget -O \"$gen_file\" \"${fetch_base_url}${gen_file}\"' exited with code $?." >&2
+                    echo "$notify_component update failed." >&2
+                    return 1
+                }
+            done
 
-        local js_file
-        for js_file in settings hfsc cake advanced rules connections custom_rules; do
-            wget -O "$QOSMATE_FRONTEND_PATH_JS/$js_file.js" "$QOSMATE_FRONTEND_URL_JS/$js_file.js" || {
-                echo "Command 'wget -O \"$QOSMATE_FRONTEND_PATH_JS/$js_file.js\" \"$QOSMATE_FRONTEND_URL_JS/$js_file.js\"' exited with code $?."
-                echo "Frontend update failed."
-                return 1
-            }
-        done
+            for exec_file in $exec_files; do
+                chmod +x "$exec_file" || {
+                    echo "Failed to make file '$exec_file' executable." >&2
+                    return 1
+                }
+            done
 
-        # !! This relies on remote file path suffix matching local file path
-        for file_path in \
-            "/usr/share/luci/menu.d/luci-app-qosmate.json" \
-            "/usr/share/rpcd/acl.d/luci-app-qosmate.json" \
-            "/usr/libexec/rpcd/luci.qosmate"; \
-        do
-            wget -O "$file_path" "${QOSMATE_FRONTEND_BASE_URL}${file_path}" || {
-                echo "Command 'wget -O \"$file_path\" \"${QOSMATE_FRONTEND_BASE_URL}${file_path}\"' exited with code $?."
-                echo "Frontend update failed."
-                return 1
-            }
-        done
+            if [ "$component" = frontend ]; then
+                for js_file in $js_files; do
+                    wget -O "$QOSMATE_FRONTEND_PATH_JS/$js_file.js" "$QOSMATE_FRONTEND_URL_JS/$js_file.js" || {
+                        echo "Command 'wget -O \"$QOSMATE_FRONTEND_PATH_JS/$js_file.js\" \"$QOSMATE_FRONTEND_URL_JS/$js_file.js\"' exited with code $?." >&2
+                        echo "$notify_component update failed." >&2
+                        return 1
+                    }
+                done
 
-        chmod +x /usr/libexec/rpcd/luci.qosmate || {
-            echo "Failed to make file '/usr/libexec/rpcd/luci.qosmate' executable."
-            return 1
-        }
+                /etc/init.d/rpcd restart
+                /etc/init.d/uhttpd restart
+            fi
 
-        echo "Frontend update complete."
+            echo "$notify_component update complete."
+        fi
+    done
 
-        /etc/init.d/rpcd restart
-        /etc/init.d/uhttpd restart
-    fi
     expand_config
 
     echo "Update complete. Please restart QoSmate."
