update(): reduce code duplication, improve error messages

diff --git a/etc/init.d/qosmate b/etc/init.d/qosmate
--- a/etc/init.d/qosmate
+++ b/etc/init.d/qosmate
@@ -502,6 +502,7 @@ check_version() {
 
 update() {
     local force_update=0
+    local file_path
 
     if [ "$QOSMATE_FORCE" = "1" ]; then
         force_update=1
@@ -544,38 +545,63 @@ update() {
     # Update backend
     if [ "$force_update" -eq 1 ] || [ "$current_backend_version" != "$latest_backend_version" ]; then
         echo "Updating backend..."
-        if wget -O /etc/qosmate.sh "$QOSMATE_BASE_URL/etc/qosmate.sh" && \
-           wget -O /etc/init.d/qosmate "$QOSMATE_BASE_URL/etc/init.d/qosmate" && \
-           wget -O /etc/hotplug.d/iface/13-qosmateHotplug "$QOSMATE_BASE_URL/etc/hotplug.d/iface/13-qosmateHotplug"; then
-            chmod +x /etc/qosmate.sh /etc/init.d/qosmate
-            echo "Backend update complete."
-        else
-            echo "Backend update failed."
+
+        # !! This relies on remote file path suffix matching local file path
+        for file_path in \
+            "/etc/qosmate.sh" \
+            "/etc/init.d/qosmate" \
+            "/etc/hotplug.d/iface/13-qosmateHotplug"; \
+        do
+            wget -O "$file_path" "${QOSMATE_BASE_URL}${file_path}" || {
+                echo "Command 'wget -O \"$file_path\" \"${QOSMATE_BASE_URL}${file_path}\"' exited with code $?."
+                echo "Backend update failed."
+                return 1
+            }
+        done
+
+        chmod +x /etc/qosmate.sh /etc/init.d/qosmate || {
+            echo "Failed to make files '/etc/qosmate.sh', '/etc/init.d/qosmate' executable."
             return 1
-        fi
+        }
+
+        echo "Backend update complete."
     fi
 
     # Update frontend
     if [ "$force_update" -eq 1 ] || [ "$current_frontend_version" != "$latest_frontend_version" ]; then
         echo "Updating frontend..."
-        if  wget -O "$QOSMATE_FRONTEND_PATH_JS/settings.js" "$QOSMATE_FRONTEND_URL_JS/settings.js" && \
-            wget -O "$QOSMATE_FRONTEND_PATH_JS/hfsc.js" "$QOSMATE_FRONTEND_URL_JS/hfsc.js" && \
-            wget -O "$QOSMATE_FRONTEND_PATH_JS/cake.js" "$QOSMATE_FRONTEND_URL_JS/cake.js" && \
-            wget -O "$QOSMATE_FRONTEND_PATH_JS/advanced.js" "$QOSMATE_FRONTEND_URL_JS/advanced.js" && \
-            wget -O "$QOSMATE_FRONTEND_PATH_JS/rules.js" "$QOSMATE_FRONTEND_URL_JS/rules.js" && \
-            wget -O "$QOSMATE_FRONTEND_PATH_JS/connections.js" "$QOSMATE_FRONTEND_URL_JS/connections.js" && \
-            wget -O "$QOSMATE_FRONTEND_PATH_JS/custom_rules.js" "$QOSMATE_FRONTEND_URL_JS/custom_rules.js" && \
-            wget -O /usr/share/luci/menu.d/luci-app-qosmate.json "$QOSMATE_FRONTEND_BASE_URL/root/usr/share/luci/menu.d/luci-app-qosmate.json" && \
-            wget -O /usr/share/rpcd/acl.d/luci-app-qosmate.json "$QOSMATE_FRONTEND_BASE_URL/root/usr/share/rpcd/acl.d/luci-app-qosmate.json" && \
-            wget -O /usr/libexec/rpcd/luci.qosmate "$QOSMATE_FRONTEND_BASE_URL/root/usr/libexec/rpcd/luci.qosmate"; then
-            chmod +x /usr/libexec/rpcd/luci.qosmate
-            echo "Frontend update complete."
-            /etc/init.d/rpcd restart
-            /etc/init.d/uhttpd restart
-        else
-            echo "Frontend update failed."
+
+        local js_file
+        for js_file in settings hfsc cake advanced rules connections custom_rules; do
+            wget -O "$QOSMATE_FRONTEND_PATH_JS/$js_file.js" "$QOSMATE_FRONTEND_URL_JS/$js_file.js" || {
+                echo "Command 'wget -O \"$QOSMATE_FRONTEND_PATH_JS/$js_file.js\" \"$QOSMATE_FRONTEND_URL_JS/$js_file.js\"' exited with code $?."
+                echo "Frontend update failed."
+                return 1
+            }
+        done
+
+        # !! This relies on remote file path suffix matching local file path
+        for file_path in \
+            "/usr/share/luci/menu.d/luci-app-qosmate.json" \
+            "/usr/share/rpcd/acl.d/luci-app-qosmate.json" \
+            "/usr/libexec/rpcd/luci.qosmate"; \
+        do
+            wget -O "$file_path" "${QOSMATE_FRONTEND_BASE_URL}${file_path}" || {
+                echo "Command 'wget -O \"$file_path\" \"${QOSMATE_FRONTEND_BASE_URL}${file_path}\"' exited with code $?."
+                echo "Frontend update failed."
+                return 1
+            }
+        done
+
+        chmod +x /usr/libexec/rpcd/luci.qosmate || {
+            echo "Failed to make file '/usr/libexec/rpcd/luci.qosmate' executable."
             return 1
-        fi
+        }
+
+        echo "Frontend update complete."
+
+        /etc/init.d/rpcd restart
+        /etc/init.d/uhttpd restart
     fi
     expand_config
 
